'use client';
import React from 'react';
import Header from '@/components/header';
import Footer from '@/components/newfooter';
import Box from '@/components/box';
import Image from 'next/image';
const WhyKW = () => {
  const sections = [
    {
      number: '01',
      title: 'Agent Focus',
      description:
        `Keller Williams differs from traditional real estate companies that primarily focus on brokerage operations.
Keller Williams places its real estate agents at the core of its business model. The company believes that its success is closely tied to the success of its agents. Therefore, Keller Williams focuses on empowering its agents and providing them with the tools and support needed to achieve their full potential.

`,
    },
    {
      number: '02',
      title: 'Profit Sharing',
      description:
       `Keller Williams operates a unique profit-sharing model that incentivizes agents to attract other productive agents to the company. Agents who refer others to join the Keller Williams team can earn a portion of the profits generated by those they sponsor. 
       This model encourages a culture of collaboration and mutual growth.`,
    },
    {
      number: '03',
      title: 'Coaching and Training',
      description:
        `Keller Williams places a strong emphasis on education and training, offering its agents numerous opportunities to develop their skills and knowledge. Keller Williams University provides a rich array of training programs and courses, both in-person and online, to meet the needs of agents at different levels. 
        Additionally, books by Gary Keller, which are valuable resources on real estate, enhance agents’ knowledge and help them succeed.`
    },
    {
      number: '04',
      title: "Technology",
      description:
        `The company invests heavily in technology to provide its agents with innovative tools to help them succeed in their business. A notable example is "KWIQ",
         a virtual assistant powered by artificial intelligence that helps agents access all Keller Williams information and tools.`,
    }
    
  ];

  const sections2 = [
    {
      number: '01',
      title: 'Extensive Network and Market Reach',
      description:
        `One of the key advantages of partnering with KW is our extensive network and market reach. As the largest real estate franchise in the world, we have a vast network of agents, investors, and potential buyers who are actively seeking new opportunities. By leveraging our network, we can connect you with the right individuals and organizations to accelerate the success of your projects.
`,
    },
    {
      number: '02',
      title: 'Expertise and Industry Knowledge',
      description:
       `KW prides itself on its highly skilled and knowledgeable agents who are experts in their respective markets.
Our agents possess a deep understanding of market trends, property valuation, and investment strategies. By collaborating with KW, you gain access to this wealth of expertise, ensuring that your projects are guided by professionals who understand the intricacies of the real estate industry.`,
    },
    {
      number: '03',
      title: 'Innovative Technology and Tools',
      description:
        `In today's digital age, technology plays a crucial role in real estate success. KW is at the forefront of innovation,
providing our agents with cutting-edge tools and platforms to streamline processes, enhance marketing efforts, and drive results. 
By partnering with KW, you gain access to our state-of-the-art technology, empowering you to stay ahead of the competition and make informed decisions.`
    },
    {
      number: '04',
      title: "Collaborative Approach",
      description:
        `At KW, we believe in the power of collaboration. We understand that successful projects require a team effort, and we are committed to working closely with you to achieve our shared goals. Our collaborative approach ensures that your vision and objectives are at the forefront of every decision, allowing us to create tailored strategies that align with your unique needs.

`,
    },
     {
      number: '05',
      title: "Joint Ventures and Projects",
      description:
        `KW has a proven track record of successful joint ventures and projects. By partnering with us, you tap into our experience and resources, 
        enabling you to explore new opportunities and expand your portfolio. Whether it's a residential development, commercial project, or mixed-use venture, KW has the expertise and network to help you navigate the complexities of joint ventures and maximize your returns.

`,
    }
    
  ];
  return (
    <div className="">
      <Header />
      <Box
        src="/why_kw_page.jpeg"
        h3="Why KW"
        image="https://static.wixstatic.com/media/36a881_a82aacde83a9442dae07d99a846cadf4~mv2.png/v1/fill/w_271,h_180,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/8-removebg-preview%20(1).png"
      />

      
<main className="px-4 py-4 md:py-12">
        <div className="max-w-full mx-auto text-center">
        
         
          <p className="text-2xl font-semibold md:text-3xl">WHY KW?</p>
           <hr className="w-32 md:w-80 mx-auto bg-[rgb(206,32,39,255)] h-[1.5px] border-0 mt-4 md:mt-8" />
        
        </div>
      </main>
      {/* Section Boxes */}
      <div className="max-w-full mx-auto  bg-gray-100">
      
        <hr className="w-full border-t border-gray-300" />
      
        {sections.map((section, index) => (
          <React.Fragment key={index}>
            {/* Mobile: stacked vertical layout */}
            <div className="md:hidden px-4 py-6 mx-6">
              <div className="text-3xl py-2 text-gray-400 font-normal mb-1">{section.number}</div>
              <div className="text-2xl font-semibold text-black mb-4 tracking-[0.1em] md:tracking-tight">{section.title}</div>
              <div className="text-sm leading-relaxed text-gray-700">{section.description}</div>
            </div>
            {/* Desktop: grid layout */}
            <div className="hidden md:grid grid-cols-12 items-stretch hover:bg-[rgb(206,32,39,255)] group transition duration-300 px-4 min-h-[120px]">
              {/* Number */}
              <div className="md:ml-30 col-span-2 md:col-span-1 flex items-center justify-center text-5xl  text-gray-500 group-hover:text-black font-normal">
                {section.number}
              </div>

              {/* Title */}
              <div className="md:ml-46 col-span-4 md:col-span-4 flex items-center text-xl font-semibold tracking-wide text-black group-hover:text-white">
                {section.title}
              </div>

               {/* Vertical Line Between Title and Description - disappears on hover */}
              <div className="col-span-1 flex justify-center">
                <div className=" ml-22 w-[1px] bg-[rgb(206,32,39,255)] h-auto md:h-28 my-4 group-hover:opacity-0 transition-opacity duration-300"></div>
              </div>

              {/* Description */}
              <div className="col-span-5 md:col-span-6 flex items-center text-[0.6rem] md:text-[1rem]  leading-relaxed text-gray-700 group-hover:text-white py-4">
                {section.description}
              </div>
            </div>
            {/* Horizontal divider between sections */}
            {index < sections.length - 1 && (
              <hr className="w-full border-t border-gray-300" />
            )}
          </React.Fragment>
        ))}
      </div>

       <main className="px-4 md:py-12 py-6">
        <div className="max-w-full mx-auto text-center">
        
         
          <p className="text-2xl font-semibold md:text-3xl">WHY KELLER WILLIAMS SAUDI ?</p>
           <hr className="w-32 md:w-80 mx-auto bg-[rgb(206,32,39,255)] h-[1.5px] border-0 mt-4 md:mt-8" />
        
        </div>
      </main>

 {/* Section Boxes */}
      <div className="max-w-full mx-auto bg-gray-100">
        <hr className="w-full border-t border-gray-300" />
        {sections2.map((section, index) => (
          <React.Fragment key={index}>
            {/* Mobile: stacked vertical layout */}
            <div className="md:hidden px-4 py-6 mx-6">
              <div className="text-3xl py-2 text-gray-400 font-normal mb-1">{section.number}</div>
              <div className="text-2xl font-semibold text-black mb-4 tracking-[0.1em] md:tracking-tight">{section.title}</div>
              <div className="text-sm leading-relaxed text-gray-700">{section.description}</div>
            </div>
            {/* Desktop: grid layout */}
            <div className="hidden md:grid grid-cols-12 items-stretch hover:bg-[rgb(206,32,39,255)] group transition duration-300 px-4 min-h-[120px]">
              {/* Number */}
              <div className="md:ml-30 col-span-2 md:col-span-1 flex items-center justify-center text-5xl  text-gray-500 group-hover:text-black font-normal">
                {section.number}
              </div>

              {/* Title */}
              <div className="md:ml-46 col-span-4 md:col-span-4 flex items-center text-xl font-semibold tracking-wide text-black group-hover:text-white">
                {section.title}
              </div>

               {/* Vertical Line Between Title and Description - disappears on hover */}
              <div className="col-span-1 flex justify-center">
                <div className=" ml-22 w-[1px] bg-[rgb(206,32,39,255)] h-auto md:h-28 my-4 group-hover:opacity-0 transition-opacity duration-300"></div>
              </div>

              {/* Description */}
              <div className="col-span-5 md:col-span-6 flex items-center text-[0.6rem] md:text-[1rem]  leading-relaxed text-gray-700 group-hover:text-white py-4">
                {section.description}
              </div>
            </div>
            {/* Horizontal divider between sections */}
            {index < sections2.length - 1 && (
              <hr className="w-full border-t border-gray-300" />
            )}
          </React.Fragment>
        ))}
      </div>

 <div className="flex flex-col items-center justify-center py-4 md:py-16">
        <Image
          src="/howwillyouthink.png"
          alt="How Will You Thrive"
          width={800}
          height={400}
          className="w-70 h-20 md:w-[800px] md:h-[400px] object-contain"
        />
      </div>

                {/* <div className=" ml-22 w-[1px] bg-[rgb(206,32,39,255)] h-auto md:h-28 my-4 group-hover:opacity-0 transition-opacity duration-300"></div> */}
     
      <Footer />
    </div>
  );
};

export default WhyKW;